name: Trigger Tests in Testing Repo

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Testing Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const repoOwner = 'gklsenthil';
            const repoName = 'e-commerce';
            const workflowFileName = 'run-tests.yml';
            const branchName = 'main';
            const token = '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';

            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: token });

            await octokit.actions.createWorkflowDispatch({
              owner: repoOwner,
              repo: repoName,
              workflow_id: workflowFileName,
              ref: branchName,
            });

      - name: Notify
        run: echo "Testing workflow triggered successfully."
